### ISSUE TITLE
Make habitat test mandatory again

### ISSUE THREAD

**Issue by SamNPowers** [facebookresearch/home-robot#123]
Yeah would be great if you can remove this, no worries if it doesn't pass locally since everything will ultimately be run on CircleCI.

_Originally posted by @exhaustin in https://github.com/facebookresearch/home-robot/pull/121#discussion_r1154750152_

**Comment by yvsriram** [comment]
A duplicate issue was created for new tests: https://github.com/facebookresearch/home-robot/issues/148
