### ISSUE TITLE
De-duplicate Function overrides in GeneralLanguageEnv, merging it with StretchPickAndPlaceEnv

### ISSUE THREAD

**Issue by zephirefaith** [facebookresearch/home-robot#196]
same as before - would be best to not dplicate code, otherwise we might see bugs creep in

_Originally posted by @cpaxton in https://github.com/facebookresearch/home-robot/pull/191#discussion_r1204522545_

**Comment by cpaxton** [comment]
@zephirefaith is this still doable?

**Comment by cpaxton** [comment]
Closing as not planned/no longer on roadmap
