### ISSUE TITLE
Any possibility to replace the usage of sophuspy

### ISSUE THREAD

**Issue by SiyuanHuang95** [facebookresearch/home-robot#252]
## 🐛 Bug

In the cluster, the user generally does not have the root right, which makes the installation of the required packs quite difficult. 

To install the sophuspy, the user needs to install pybind previously and link many static libraries, which would be difficult for the guys without root.

**Comment by SiyuanHuang95** [comment]
Also, one very interesting thing is that, it seems that you did not use sophuspy actually in the source code.

**Comment by yvsriram** [comment]
Yes, you are right. It is not used anywhere and will be removed from the list of requirements.

**Comment by SiyuanHuang95** [comment]
Cool, thanks!

**Comment by yvsriram** [comment]
It seems like `sophuspy` is actually imported in files under `src/home_robot` (as `import sophus`).  Also, these functions are being used in `discrete_planner`. So the dependency cannot be trivially removed.

**Comment by yvsriram** [comment]
Are you still facing issues installing this dependency?

**Comment by SiyuanHuang95** [comment]
To be honest, I did not successfully install the home-robot on the slurm.

But, I somehow make it in one workstation where I have sudo rights.

**Comment by cpaxton** [comment]
What issues are you still having?

**Comment by SiyuanHuang95** [comment]
@cpaxton sophuspy needs pybind, pybind needs make and install, which needs the sudo rights.
