### ISSUE TITLE
Documentation for the respository

### ISSUE THREAD

**Issue by Chortine** [facebookresearch/home-robot#276]
Hi, is there any documentation that explans systematically the configs files in this repository as well as the dataset json files?

For instance, I am currently lost when try to shuffle the room or assign a specific room while running the home-robot/projects/habitat_ovmm/eval_baselines_agent.py

Thank you !

**Comment by yvsriram** [comment]
Hi, thanks for the question.

For the config files in this repository, we do have comments (eg. [heuristic_agent.yaml](https://github.com/facebookresearch/home-robot/blob/main/projects/habitat_ovmm/configs/agent/heuristic_agent.yaml)) explaining fields that are not self-explanatory.

For the dataset json files, we describe the important fields [on hugging face](https://huggingface.co/datasets/ai-habitat/OVMM_dataset). 

> For instance, I am currently lost when try to shuffle the room or assign a specific room while running the home-robot/projects/habitat_ovmm/eval_baselines_agent.py

The HSSD dataset we are using currently does not have room annotations. So assigning a specific room (eg. kitchen, living room) would not be possible.

Please let us know if you have any other specific questions.

**Comment by cpaxton** [comment]
I'm going to close this for tracking; please re-open it if you have further questions
