### ISSUE TITLE
Robotic arm documentation missing for home-robot-sim

### ISSUE THREAD

**Issue by SgtVincent** [facebookresearch/home-robot#300]
## 🚀 Feature

- Description of how to control robot arm joints and end effector in the simulation. 
- (bonus) Some example scripts to demonstrate possible use cases would be better. 

## Motivation
Great help for OVMM 2023 challenge onboard.  🚀 🚀 🚀

**Comment by yvsriram** [comment]
Thanks for raising the issue.

> - Description of how to control robot arm joints and end effector in the simulation.


You can find details of the joint space [ncluding arm joints and end effector [here](https://github.com/facebookresearch/home-robot/blob/e8e3425824a391f2119989004272f54397d949b5/src/home_robot/home_robot/motion/stretch.py#L911), but we will document these as well.

> - (bonus) Some example scripts to demonstrate possible use cases would be better.

Can you please elaborate on this a bit or provide examples? Is this specific to arm actions?
