### ISSUE TITLE
RL-based "Pick" skill support missing from OVMM environment 

### ISSUE THREAD

**Issue by SgtVincent** [facebookresearch/home-robot#301]
Hi there, 

I am reading through your document & code for OVMM challenge. It looks like ovmm_agent does not support `rl`-type "pick" skill yet in the simulation:
- For evaluation, in `ovmm_agent.py`, `AGENT.SKILLS.PICK.type = "rl"` leads to `NotImplementedError` https://github.com/facebookresearch/home-robot/blob/7c0a4dca0293fea2023a56ca3411d1e83a59edce/src/home_robot/home_robot/agent/ovmm_agent/ovmm_agent.py#L428
- Also from the OVMM readme, training pick skill is not enabled for now: https://github.com/facebookresearch/home-robot/blob/7c0a4dca0293fea2023a56ca3411d1e83a59edce/projects/habitat_ovmm/README.md?plain=1#L105

I am wondering when do you plan to enable this feature for the OVMM challenge. I think this skill is necessary for the OVMM challenge, right? 

Thanks in advance.

**Comment by cpaxton** [comment]
Habitat doesn't support training dynamic pick skills, so we assume the existence of a pick skill on the robot - similar to ALFRED. There is a real-world pick skill that you can use.
