### ISSUE TITLE
Change the scene

### ISSUE THREAD

**Issue by Chortine** [facebookresearch/home-robot#329]
Hi team,

When I run the eval_baselines_agent.py, the scene is randomly chosen among the val scenes. How can I properly change the config to make sure that only one specific scene is used? 

Thanks.

**Comment by cpaxton** [comment]
you can pass it as an argument into the baseline agent:
```
python projects/habitat_ovmm/eval_baselines_agent.py \
  habitat.dataset.episode_ids="[0]"
```

**Comment by yvsriram** [comment]
Closing this issue. Please reopen if this is not solved yet.
