### ISSUE TITLE
OVMM Challenge Docker Container Ubuntu Version

### ISSUE THREAD

**Issue by trangml-mit** [facebookresearch/home-robot#330]
## 🐛 Bug

Right now the homerobot-ovmm-challenge-2023 Docker container is using Ubuntu 22.04, which is problematic, as it does not support ROS Noetic.

## Expected behavior

The docker container should be Ubuntu 20.04, consistent with the preliminary README instructions [https://github.com/facebookresearch/home-robot#preliminary](https://github.com/facebookresearch/home-robot#preliminary)

> HomeRobot requires Python 3.9. Installation on a workstation requires [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) and [mamba](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html). Installation on a robot assumes Ubuntu 20.04 and [ROS Noetic](http://wiki.ros.org/noetic).

**Comment by cpaxton** [comment]
@trangml-mit do you need Noetic for simulation evaluations?

**Comment by trangml-mit** [comment]
Yes, for our solution we plan on using a mapping technique/software that needs Noetic.

**Comment by cpaxton** [comment]
Is there any chance of building from source for now, or using ROS2? We'll work on getting that supported

**Comment by rpartsey** [comment]
Hi @trangml-mit, thanks for reporting this!
Can you, please, try using `fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023-ubuntu20.04` Docker image as a base image for your submission and let us know if it resolves your issue?

**Comment by cpaxton** [comment]
Should be resolved; re-open if there are any issues

**Comment by trangml-mit** [comment]
Sorry, just got around to testing this, but it doesn't appear that I can pull the `fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023-ubuntu20.04` image, and I don't see it when I view it here [https://hub.docker.com/r/fairembodied/habitat-challenge/tags](https://hub.docker.com/r/fairembodied/habitat-challenge/tags). Was it made public?

**Comment by cpaxton** [comment]
Reopening the issue until we can verify it's fixed

**Comment by cpaxton** [comment]
@rpartsey might not have been pushed?

**Comment by rpartsey** [comment]
Oh, sorry for that @trangml-mit and @cpaxton. Should be available now.
