### ISSUE TITLE
When info is None

### ISSUE THREAD

**Issue by Chortine** [facebookresearch/home-robot#336]
## 🐛 Bug
Hi team,

![image](https://github.com/facebookresearch/home-robot/assets/107395103/427005be-c0b7-4bb4-954a-9ed6bc6cb849)

In src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py, maybe it was better if we add an if condition here to filter out the case that info is None?

**Comment by cpaxton** [comment]
Merged #337
