### ISSUE TITLE
Habitat env observation details

### ISSUE THREAD

**Issue by Yonggie** [facebookresearch/home-robot#363]
## 🚀 Feature
Via checking the initial observations given by environment, I can find the ``object_embedding`` variable as the target object goal in the shape of ``(512,1)``(If I'm not wrong?). Could I find an object image of the goal object from the observations (like image nav does)?

![图片](https://github.com/facebookresearch/home-robot/assets/31330044/5997c1d2-895e-4587-a474-2e249ffc50d2)

If the observations do not have it, are we allowed to define new oberservations and make it return new items that we added and any suggestions how we change the env config to achieve it?

**Comment by yvsriram** [comment]
> If the observations do not have it, are we allowed to define new oberservations and make it return new items that we added and any suggestions how we change the env config to achieve it?

Yes, the observations do not have an image of the goal. This is privileged information. In this task, we are trying to find objects just by their names. Moreover, an object goal can't be represented by a single image - the scene could have multiple correct instances of the goal object category.

You are not allowed to modify the observation dict the agent receives from the environment. The EvalAI remote evaluation expects that the agents function with the same environment.
