### ISSUE TITLE
What the OVMM specific instructions locates?

### ISSUE THREAD

**Issue by FUIGUIMURONG** [facebookresearch/home-robot#369]
I want to ask whether it has the specific instructions dateset,  like "Move toy animal from chair to table" or more high-level instruction like "I spilled the milk, can you help? ".

**Comment by yvsriram** [comment]
Hi, the instructions are in the form of a tuple: "Move <object_category> from <start_receptacle> to <end_receptacle>". We do not feed in high-level instructions.

**Comment by cpaxton** [comment]
Specifically a task is specified as the tuple (object, start_receptacle, goal_receptacle) as described in our paper: https://ovmm.github.io/
