### ISSUE TITLE
What does one timestep correspond to?

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/home-robot#372]
Hello,

I wanted some clarity on the concept of a timestep. As the simulator is physics enabled, I can understand that the motion will be continuous. In that respect, I found a value of timestep in /home-robot/data/default.physics_config.json which is 0.008. But when I ran the baseline for habitat-ovmm callenge evaluation, I saw consecutive frames with huge displacement between them. Does that mean the robot moves that much (20-30 degrees) in that time? Or is it an aggregation of multiple steps.

Also I assume the robot physics will not allow sharp turns such as left followed by a sharp right, as the robot inertia will play a part. Is the inertia less or disabled in the baseline? Or possibly I made a mistake in building it? Attaching two consecutive frames from the baseline evaluation.
![snapshot_001](https://github.com/facebookresearch/home-robot/assets/5046399/c9f8ca77-3817-4d26-b215-0c04b0bdaf4d)
![snapshot_002](https://github.com/facebookresearch/home-robot/assets/5046399/f99cf73e-3e22-4bc2-ae26-832c19228641)

**Comment by cpaxton** [comment]
Timesteps are arbitrary amounts of time, since we send a command to the low-level controller at each point. On the real robot they can be relatively large. There won't be any problems executing such a command on the real robot.

**Comment by ruddradev** [comment]
Thank you, this clarifies the query.
