### ISSUE TITLE
Invalid type <class 'NoneType'> for key WEIGHT_DECAY_BIAS when importing DeticPerceptron

### ISSUE THREAD

**Issue by gitatwork19** [facebookresearch/home-robot#393]
## 🐛 Bug
I'm currently testing our Docker image for submission by using the eval_baselines_agent.py in habitat_ovmm but I'm getting  an error related to the WEIGHT_DECAY_BIAS parameter.  

## Steps to Reproduce

Docker Base Image: fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023
home-robot version: @cpaxton 's [update-docker-v0.2](https://github.com/facebookresearch/home-robot/tree/cpaxton/update-docker-v0.2/projects/habitat_ovmm) branch

Followed the steps for submission here: https://github.com/facebookresearch/home-robot/blob/744b06ff6bb0c80f1417884b35de69cbc8252b6f/docs/challenge.md#local-evaluation

The Docker image runs successfully but once it starts running the agent I get this error:

https://pastebin.com/pzaeUGQf

**Comment by yvsriram** [comment]
@gitatwork19 were you able to run evaluations outside of docker with the [demo command](https://github.com/facebookresearch/home-robot/tree/main/projects/habitat_ovmm#demo-setup)?

**Comment by yvsriram** [comment]
May I please know the base docker version you are using and the OS+version of the system you are running this on?

**Comment by gitatwork19** [comment]
Docker Version: 24.0.5
Docker Base Image: fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023
OS: Ubuntu 20.04

I had the same results on another machine with Ubuntu 22.04

**Comment by cpaxton** [comment]
Agent is in fact working for me
```opt/conda/envs/home-robot/lib/python3.9/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Loading pretrained CLIP
 10%|█         | 1/10 [01:05<09:46, 65.19s/it][15:46:05:807839]:[Core] ManagedContainerBase.h(329)::checkExistsWithMessage : <Lighting Layout>::getObjectByHandle : Unknown Lighting Layout managed object handle :  . Aborting
```

**Comment by cpaxton** [comment]
Testing w/ same docker version, ubuntu 20.04

**Comment by gitatwork19** [comment]
Thanks @cpaxton and @yvsriram . By main branch, is it  the main branch of the existing repository in the image or should I git pull and checkout main? The one in the container's using update-docker-v0.02 branch https://hub.docker.com/layers/fairembodied/habitat-challenge/homerobot-ovmm-challenge-2023/images/sha256-d5c0f19ad8ae6ab2f3e4e4f1be0905c0db4d0eb693755ace231b48f153b5f215?context=explore

**Comment by cpaxton** [comment]
Are you sure that you have the most up to date version of the docker image?

**Comment by yvsriram** [comment]
Please pull the latest docker image using `docker pull fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023`

**Comment by yvsriram** [comment]
Can you please try this image `fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023-ubuntu20.04` and see if it works?

**Comment by gitatwork19** [comment]
I'll try that. Will keep you guys posted. Thanks

**Comment by gitatwork19** [comment]
I migrated my Docker file to use the recommended base image `fairembodied/habitat-challenge:homerobot-ovmm-challenge-2023-ubuntu22.04`  but the problem still persists. 

I also added the following on my Docker file just to make sure im using the main branch

```
WORKDIR /home-robot
RUN git pull
RUN git checkout main 
RUN pip install -e src/home_robot
```
but the same problem persists. 

Should I pull a specific version for src/third_party/detectron2/detectron2?

**Comment by yvsriram** [comment]
We have been using this version: https://github.com/facebookresearch/detectron2/tree/38af375052d3ae7331141bc1a22cfa2713b02987. Can you check if you are using the same commit as well?

**Comment by gitatwork19** [comment]
Fixed by upgrading yacs . https://github.com/facebookresearch/detectron2/issues/3649#issuecomment-1020689563 . Thanks for helping

**Comment by cpaxton** [comment]
@gitatwork19 was there a problem with our yacs version? anything you suggest adding to Readme?

**Comment by grassjelly** [comment]
I think it's a problem on my side. I did a conda update during build time which messed up the dependencies. I removed it and works out of the box. Thanks @cpaxton
