### ISSUE TITLE
Request for Additional Resources

### ISSUE THREAD

**Issue by peryion** [facebookresearch/home-robot#403]
## 🐛 Bug

During the evaluation of our Docker image on EvalAI, we encountered a timeout issue. To address this, we kindly request a substantial extension of the testing time to about 100 hours.

**Comment by peryion** [comment]
[https://drive.google.com/file/d/1EbCx3vtce8NCLkxsLW7doSmLo75H7dKm/view?usp=drive_link](url)

**Comment by peryion** [comment]
![GitHub Logo](https://github.com/peryion/votenet/blob/master/%E6%88%AA%E5%B1%8F2023-09-30%2008.54.18.png)

**Comment by yvsriram** [comment]
Thanks, for giving the estimate of the time you need. We will check if this is possible and get back soon.

**Comment by yvsriram** [comment]
We have extended it. Please try again.

**Comment by peryion** [comment]
Thanks for your response. I tried again, but it still times out after running for 72 hours.
Test challenge phase and Test standard phase.

**Comment by yvsriram** [comment]
@peryion can you please share your team name on EvalAI?

@gchhablani any idea why it times out after 72 hours?

**Comment by peryion** [comment]
I submit my solution on Oct 8, 2023 3:41:44 PM for test challenge phase and on Oct 1, 2023 6:59:30 AM for test standard phase. But they all time out.

my team name is GVL

**Comment by peryion** [comment]
When I submitted the heuristic baseline for testing, it took 60 hours, and I estimated that my solution would take around 100 hours to complete the testing. However, it timed out at 72 hours.

The testing time for my solution is approximately 1.5 times that of the heuristic baseline.

**Comment by gchhablani** [comment]
@peryion I had verified that the evaluation time was 100 hours for other submissions. Can you please share if this was a fresh submission or a rerun? Can you please also share the submission ID for which you are facing this issue?

Thanks!

**Comment by peryion** [comment]
It was a rerun submission.  I haven't updated my code to the latest version. Its commit is 645a338. 
Do I need to update my code, or make some changes?

Submission ID: 309068 for test standard phase, 309776 for test challenge phase.

**Comment by gchhablani** [comment]
@peryion This issue is fixed.

**Comment by peryion** [comment]
Thanks! I will try it again.

**Comment by gchhablani** [comment]
@peryion That's strange. Does it still timeout with 72 hours?

**Comment by peryion** [comment]
Yes, it timed out at 72 hours.

**Comment by cpaxton** [comment]
Maybe we can re run it? Can you share submission id and all other relevant information?
________________________________

**Comment by cpaxton** [comment]
Closing this issue now that competition is done and the issue was resolved
