### ISSUE TITLE
If the submitted test-challenge program runs over 48 hours, will the results be canclled?

### ISSUE THREAD

**Issue by yansenhan** [facebookresearch/home-robot#419]
Is there any rules for over-48-hour results?

If the test-challenge program runs over 48 hours, what will the official process be? cancel the results or have any other evalutation methods?

**Comment by yvsriram** [comment]
The evaluations should be able to run for 100 hours. If your solution takes more time, it will result in a timeout and will not be considered. But please let us know if you run into timeout issues.
