### ISSUE TITLE
OVMM test timeout

### ISSUE THREAD

**Issue by peryion** [facebookresearch/home-robot#428]
I try to submit docker image to evalai for evaluation, but it times out after running for 72 hours both for the Test challenge phase and Test standard phase.

But @yvsriram said the evaluations should be able to run for 100 hours.

Should I modify my code, or just simply submit the previous Docker image to test for a extened time.

**Comment by yvsriram** [comment]
Unresolved in #403

**Comment by cpaxton** [comment]
closing as with #403 since we resolved this on the evalai side
