### ISSUE TITLE
Placed object on receptical but overall_success == 0

### ISSUE THREAD

**Issue by LebinDing749** [facebookresearch/home-robot#430]
## 🐛overall_success bug

The robot have palced the object on the receptical, but, after over 50 timesteps it was still be identified as 'overall_success': 0.0
I encountered several cases like this. If the success condition is not clear? Or, I misunderstand the success condition?
 
the snapshot_pngs are here: (episode_id = 512, ground_truth = 1)
snapshot_117.png, snapshot_121.png and snapshot_217.png. 
![snapshot_117.png](https://github.com/LebinDing749/Images_repo/raw/main/ovmm/scene_512/snapshot_117.png)
![snapshot_121.png](https://github.com/LebinDing749/Images_repo/raw/main/ovmm/scene_512/snapshot_121.png)
![snapshot_217.png](https://github.com/LebinDing749/Images_repo/raw/main/ovmm/scene_512/snapshot_217.png)

**Comment by yvsriram** [comment]
Hi, thanks for creating the issue. The failures could be because of robot-scene collisions or the object not coming to rest.

Can you check these metrics?
`END.robot_collisions.robot_scene_colls`
`END.picked_object_angular_vel`
`END.picked_object_linear_vel`

**Comment by LebinDing749** [comment]
Thanks,
I read the episode_result.json

"END.robot_collisions.robot_scene_colls": 2.0,
"END.picked_object_angular_vel": 0.0,
"END.picked_object_linear_vel": 0.0,

Can you explain what these parameters mean?
