### ISSUE TITLE
Can we get intermediate metrics for Test Standard and Minival?

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/home-robot#432]
## 🚀 Feature
Hello, in the Evalai results, it will be helpful if we can get the breakdown of partial success like we get locally, for example, the success we get in Find Object phase, find receptacle phase etc.

This will save us time to run these locally if we already have an evalai result.

**Comment by gchhablani** [comment]
@ruddradev Thanks for pointing this out. I'll look into this, although I am not sure if this feature can be delivered before the deadline.

**Comment by cpaxton** [comment]
@gchhablani should we close this?
