### ISSUE TITLE
Submitted image got timed out after 72 hours of execution

### ISSUE THREAD

**Issue by ruddradev** [facebookresearch/home-robot#436]
## 🐛 Bug

I had submitted an entry in the test-challenge phase which got timed out due to some reason. The total execution time showed as 72 hours which is less than the specified 100 hours. 

## Steps to Reproduce

Evalai Submission ID - 310138

## Expected behavior

Submission should run for 100 hours.

**Comment by cpaxton** [comment]
Thanks for the comment. Looking into this

**Comment by gchhablani** [comment]
@rudradev

There was some issue with some of submissions which were taking the previous specified limit (72 hours). I will check if I can re-run this submission and get back.

**Comment by cpaxton** [comment]
@gchhablani can you confirm we are re-running this?

**Comment by gchhablani** [comment]
@cpaxton @ruddradev Yes, we are re-running the submission.

**Comment by cpaxton** [comment]
In that case closing this issue. Good luck @ruddradev
