### ISSUE TITLE
This repository is over its data quota

### ISSUE THREAD

**Issue by kellyiss** [facebookresearch/home-robot#437]
when I install 
 Home robot dependency for velocity controllers
home-robot @ git+ssh://git@github.com/facebookresearch/home-robot.git@habitat-challenge-2023#subdirectory=src/home_robot

I got this error. What can I do to resolve it?
 Resolved ssh://****@github.com/facebookresearch/home-robot.git to commit c5b5e25ce402cce44b7315f5303e941ea9a3d252
 Running command git submodule update --init --recursive -q
 Downloading habitat_stretch/meshes/base_link.obj (594 KB)
 Error downloading object: habitat_stretch/meshes/base_link.obj (a41840c): Smudge error: Error downloading habitat_stretch/meshes/base_link.obj (a41840c67f1c7ab0069c9d95748bd0122682e9f026b3d35dbc18423c7c5d5435): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Comment by cpaxton** [comment]
I think this is on my end, i need to move this file out of my personal github account. Will do so asap.

**Comment by cpaxton** [comment]
I will provide a zip file for now

**Comment by cpaxton** [comment]
For now, please clone the other submodules individually

**Comment by cpaxton** [comment]
@kellyiss it was added here: https://github.com/facebookresearch/home-robot/tree/main/assets/hab_stretch

Since it's fixed on main, I think I will close this issue - although @yvsriram maybe we should update this in the challenge branch if we expect it to be longer lived?

**Comment by cpaxton** [comment]
For now please copy these files from main

**Comment by kellyiss** [comment]
Thanks for your help.

**Comment by sai-prasanna** [comment]
@cpaxton I am trying to install the challenge branch of habitat and ran into this error, should I edit the extra requires of habitat-lab package to point to main branch of home-robot?
