### ISSUE TITLE
Recording Camera Poses

### ISSUE THREAD

**Issue by user432** [facebookresearch/home-robot#442]
Hello, I'm trying to record some camera pose trajectories of multiple HSSD scenes from [here](https://github.com/facebookresearch/home-robot/blob/4b3c1e1bfa9e7218d3c5e09ee257f05c57c9be8d/src/home_robot_sim/home_robot_sim/env/habitat_ovmm_env/habitat_ovmm_env.py#L156). When I try to use the same trajectory to render frames in Blender, it doesn't seem to work. I would like to know if there's any transformation matrix I'm missing here. Thanks!

**Comment by yvsriram** [comment]
Thanks for the issue @user432! Yes, we are fixing this to be relative to the agent's start position in the episode so you can use it without further transformation for your purpose. I will let you know once it's done.

**Comment by user432** [comment]
Thanks a lot @yvsriram, it worked. Closing this issue
