### ISSUE TITLE
Viewpoints generation for custom objects

### ISSUE THREAD

**Issue by asfandasfo** [facebookresearch/home-robot#446]
I am considering the ObjectGoal navigation task and I would like to add some custom objects in the environment. I see that a list of viewpoints being used to train the robot to reach the object at a specific location and angle. Is there a way to generate these viewpoints for a custom object placed in a new position?

**Comment by yvsriram** [comment]
Hi, please follow the instructions here to generate viewpoints: https://github.com/facebookresearch/habitat-lab/tree/ovmm_main_merge/habitat-lab/habitat/datasets/rearrange#ovmm-episode-modification-script.

This will add the viewpoints here: https://github.com/facebookresearch/habitat-lab/blob/5053e666e5c9b68de70b0c28dc14f043eacc2582/habitat-lab/habitat/datasets/rearrange/modify_episodes_for_object_rearrange.py#L367
