### ISSUE TITLE
Python version needed on the robot

### ISSUE THREAD

**Issue by benoit-robotics** [facebookresearch/home-robot#447]
In the readme, you explain that your package requires Python 3.9. On the robot, only Python 3.8 is installed and your instructions for setting up the robot https://github.com/facebookresearch/home-robot/blob/home-robot-ovmm-challenge-2023-v0.1.2/docs/install_robot.md don't mention installing Python 3.9. 

Could you confirm please that Python 3.9 is required on the robot as well ?
Thank you

**Comment by yvsriram** [comment]
@Jdvakil can you please confirm?

**Comment by Jdvakil** [comment]
@benoit-robotics Python 3.9 is not required for the robot, my robot is using python 3.8.10 and it has been running fine.
