### ISSUE TITLE
GOAT Evaluation Dataset

### ISSUE THREAD

**Issue by K0uya** [facebookresearch/home-robot#450]
Hi! Thank you for your work.

Although I would like to run goat on simulator, the data is missing and it causes an error.
Could you give me the data or how may I get the one?

https://github.com/facebookresearch/home-robot/blob/goat-sim/src/home_robot_sim/home_robot_sim/env/habitat_goat_env/habitat_goat_env.py#L132

**Comment by mukulkhanna** [comment]
@K0uya GOAT-sim is currently under development. We are aiming to do a code release in a month or so.

**Comment by johncruyff14** [comment]
@mukulkhanna Hi there! Could you share this json file along with your data in google drive or some other ways? 🥰  It does not take long time and we do urgently need the data to evaluate it

**Comment by www-Ye** [comment]
> Hi! Thank you for your work.你好！谢谢你的工作。
> 
> Although I would like to run goat on simulator, the data is missing and it causes an error.虽然我想在模拟器上运行山羊，但数据丢失并导致错误。 Could you give me the data or how may I get the one?你能给我数据吗，或者我怎样才能得到数据？
> 
> https://github.com/facebookresearch/home-robot/blob/goat-sim/src/home_robot_sim/home_robot_sim/env/habitat_goat_env/habitat_goat_env.py#L132

Hi! Did you solve this data problem?

**Comment by yvsriram** [comment]
It has been released here: https://github.com/Ram81/goat-bench
