### ISSUE TITLE
can not find the modular_goat_hm3d.yaml file in the goat branch

### ISSUE THREAD

**Issue by wzjscut** [facebookresearch/home-robot#460]
HI all

I want to learn the paper GOAT and recurrent the code so I clone the goat branch. 
But when I run the command python projects/habitat_goat/eval_episode.py, I found there is no such a file modular_goat_hm3d.yaml. What should I do?

**Comment by wzjscut** [comment]
i have found it in habitat-lab, goat branch

**Comment by Yangye0526** [comment]
Hello, I solved the same problem as you when reproducing, but I found that the scene dataset is missing. Have you solved it yet
