### ISSUE TITLE
Error when submodule loaded by git

### ISSUE THREAD

**Issue by Moresweet** [facebookresearch/home-robot#475]
## 🐛 Bug

Hello, I get "Page not found" when clicking src/third_party/spot-sim2real @ 1cecb34. And the bash file install_deps.sh will report error until row 79. Although I modify the .gitmoudles from Jdvakil/spot-sim2real to facebookresearch/spot-sim2real, it still not work. the branch called no-habitat havn't been found.
![image](https://github.com/facebookresearch/home-robot/assets/47547828/124cdac9-12b6-4ea5-92e9-2f49f644b477)

## Steps to Reproduce

command:
`./install_deps.sh`

## Expected behavior

fatal: 远程错误：upload-pack: not our ref 1cecb34f5a3e52119baec35bbc9d48bf48e06431
获取了子模组路径 'src/third_party/spot-sim2real'，但是它没有包含 1cecb34f5a3e52119baec35bbc9d48bf48e06431。直接获取该提交失败。

## Additional context

I think it is caused by the project sim2real has moved to facebookresearch/sim2real while the home-robot's submodule is old.

**Comment by yvsriram** [comment]
@Jdvakil It seems like the referenced commit (`1cecb34`) is private. Is there a public commit we could use here?

Also, @Moresweet this submodule should not be necessary if you are not working with real Spot.

**Comment by Jdvakil** [comment]
Checking it out

**Comment by Jdvakil** [comment]
Should be fixed with #495
