### ISSUE TITLE
Missing submodule spot-sim2real

### ISSUE THREAD

**Issue by ramkumarkoppu** [facebookresearch/home-robot#476]
## Steps to Reproduce

In the home-robot repo, run `$HOME_ROBOT_ROOT/projects/habitat_ovmm/install.sh`

## Expected behavior

if this submodule is needed then it should be available, if not remove it from https://github.com/facebookresearch/home-robot/blob/main/.gitmodules

## Additional context
https://github.com/Jdvakil/spot-sim2real/tree/1cecb34f5a3e52119baec35bbc9d48bf48e06431 doesn't exist in https://github.com/facebookresearch/home-robot/tree/main/src/third_party

**Comment by yvsriram** [comment]
Duplicate #475 

This module is only needed for real Spot. It is not necessary for OVMM simulation or real experiments. We will fix this.
