### ISSUE TITLE
IndexError:

### ISSUE THREAD

**Issue by libaiwanovo** [facebookresearch/home-robot#484]
Thank you and your team for the excellent work. When I run `python projects/habitat_ovmm/eval_baselines_agent.py --env_config projects/habitat_ovmm/configs/env/hssd_demo.yaml`, I encounter the following error, and it occurs every time when it reaches the 74th round. Is it a data issue? Looking forward to your answer.
![74](https://github.com/facebookresearch/home-robot/assets/153749298/beb1ad49-cd69-42e1-a7e6-f348fe1d60e7)

**Comment by yvsriram** [comment]
Hey, is this something you are running into consistently? Please try the patch, it should not give this error.
