### ISSUE TITLE
Non-resolved comments in a merged PR

### ISSUE THREAD

**Issue by exhaustin** [facebookresearch/home-robot#52]
Some design issues along with minor nits #36 were pointed out after the merge.
Would be ideal to create another PR to address them.

**Comment by cpaxton** [comment]
https://github.com/facebookresearch/home-robot/issues/71
https://github.com/facebookresearch/home-robot/issues/70
https://github.com/facebookresearch/home-robot/issues/69
https://github.com/facebookresearch/home-robot/issues/68
https://github.com/facebookresearch/home-robot/issues/67
