### ISSUE TITLE
Questions about evaluating configuration

### ISSUE THREAD

**Issue by HaijieCao** [facebookresearch/home-robot#522]
Hi, how are you? 
I'd like to know how None, shown in Table 3 of the paper, is implemented in code (with RL and Heuristic and None below the skills in the table). Did you comment out the content below the corresponding skill or modify the type parameter or implement it in some other way?
I have provided the details of Table 3 and the code for the GAZE section below for your convenience.
![Table_3](https://github.com/user-attachments/assets/983dcccb-8e43-405e-98b0-cd20d620b803)
![GAZE](https://github.com/user-attachments/assets/4e7a7889-5c62-4840-872d-c291cddfee5f)

**Comment by yvsriram** [comment]
Hello,

You can skip skills like this: https://github.com/facebookresearch/home-robot/blob/ede6a67a2d0c0c8e12ad3b9726f330cea6cf90f5/projects/habitat_ovmm/configs/agent/heuristic_agent.yaml#L163 

We specify a set of skills to skip in the config.

**Comment by HaijieCao** [comment]
> Hello,
> 
> You can skip skills like this:
> 
> https://github.com/facebookresearch/home-robot/blob/ede6a67a2d0c0c8e12ad3b9726f330cea6cf90f5/projects/habitat_ovmm/configs/agent/heuristic_agent.yaml#L163
> 
> We specify a set of skills to skip in the config.

OK thank you for your reply
