### ISSUE TITLE
The show_point_cloud function is duplicated

### ISSUE THREAD

**Issue by srama2512** [facebookresearch/home-robot#65]
The `show_point_cloud` function is repeated in three different files:

https://github.com/facebookresearch/home-robot/blob/91a24315abd505929c15ad12598494a521153457/src/home_robot/home_robot/utils/image.py#L160-L170

https://github.com/facebookresearch/home-robot/blob/91a24315abd505929c15ad12598494a521153457/src/home_robot/home_robot/utils/point_cloud.py#L29-L38

https://github.com/facebookresearch/home-robot/blob/91a24315abd505929c15ad12598494a521153457/src/home_robot/home_robot/utils/data_tools/point_cloud.py#L28-L37

**Comment by cpaxton** [comment]
Should now be resolved by https://github.com/facebookresearch/home-robot/pull/58
