### ISSUE TITLE
Factor out current implementation of `compute_ik_opt` from `PinocchioIKSolver` to `UnderactuatedIKSolver` and make `PinocchioIKSolver` more generic.

### ISSUE THREAD

**Issue by zephirefaith** [facebookresearch/home-robot#84]
## 🚀 Feature
Addresses comments in #76 re:niche use-case of optimizing for only 5 joints.

## Motivation
Makes `PinocchioIKSolver` more generic for use across Stretch stack.

**Comment by exhaustin** [comment]
Resolved in https://github.com/facebookresearch/home-robot/pull/76/commits/bf372659833973bcc528541a3711eb7ce1e54716
